baseURL = "https://blog.brujordet.no/"
languageCode = "en-us"
title = "Automate attention"
author = "Anders Brujordet"
theme = "m10c"
[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML","RSS"]
  taxonomyTerm = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[params]
  avatar = "avatar.png"
  description = "Tools and techniques I use to make life easier"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/brujoand"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/brujoand"
  [[params.social]]
    name = "github"
    url = "https://www.github.com/brujoand"

[markup]
  [markup.highlight]
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
